import type { Metadata } from "next";
import { Plus_Jakarta_Sans } from "next/font/google";
import "./globals.css";
import { Footer, Header } from "@/components/layout";
import { AnnouncementBar } from "@/components/AnnouncementBar";
export const metadata: Metadata = {
 title: "Verbox Next App",
 description: "Generated by create next app",
 icons: {
  icon: "/site/footer-logo.svg",
 },
};

const inter = Plus_Jakarta_Sans({ subsets: ["latin"] });

export default function RootLayout({
 children,
}: Readonly<{
 children: React.ReactNode;
}>) {
 return (
  <html lang="en">
   <body className={`${inter.className} antialiased`}>
    <AnnouncementBar />
    <Header />
    {children}
    <Footer />
   </body>
  </html>
 );
}
